language: generic
#sudo: required # Execute with permissions, because docker stuff need it, but it is deprecated I guess
services: # Travis will understand that we use docker, so we need docker CLI.
  - docker  # Behind the scene will install a copy of docker into our running container

before_install:
  - docker build -t davitvardanyan/dav-cra -f Dockerfile.dev .

script:
  - docker run -e CI=true davitvardanyan/dav-cra npm run test

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "dav-cra-aws"
#  env: "docker-prod"
#  bucket_name: "elasticbeanstalk-us-west-2-2534233"
#  bucket_path: "dav-cra-aws"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY_ID
#  secret_access_key: $AWS_ACCESS_KEY