# Choose alpine distribution of node
FROM node:alpine

# Create a workdir inside the container
WORKDIR '/app'

# Copy package.json file to /app/ folder
COPY package.json .

# Install deps
RUN npm install

# Copy the project
COPY . .

# Run the project
CMD ["npm", "start"]